name: Bug Report
description: Report a bug or unexpected behavior in SpyHunt
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us identify and fix the issue.
        
        **Important**: For security vulnerabilities, please do not create a public issue. Instead, email pymmdrza@gmail.com directly.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I am using the latest version of SpyHunt
          required: true
        - label: I have searched existing issues to ensure this bug has not already been reported
          required: true
        - label: I have read the [documentation](https://spyhunt.readthedocs.io)
          required: true
        - label: This is not a security vulnerability (those should be emailed to pymmdrza@gmail.com)
          required: true

  - type: input
    id: version
    attributes:
      label: SpyHunt Version
      description: What version of SpyHunt are you using? Run `spyhunt --version` or check `pip show spyhunt`
      placeholder: "e.g., 4.0.10"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened was...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Run command '...'
        2. Use option '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Stack Trace
      description: |
        If applicable, paste any error messages, stack traces, or relevant log output.
        Check `spyhunt.log` for detailed logs.
      render: shell
      placeholder: Paste error logs here...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using? Run `python --version`
      placeholder: "e.g., Python 3.9.7"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Any additional environment details that might be relevant
        (e.g., virtual environment, Docker, specific network configuration)
      placeholder: |
        - Using virtual environment: yes/no
        - Installation method: pip/source
        - Network: corporate/home/cloud

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        Screenshots, configuration files, or additional information that might help.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I am willing to submit a pull request to fix this bug
