name: Feature Request
description: Suggest a new feature or enhancement for SpyHunt
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature or enhancement!
        
        Please provide as much detail as possible to help us understand your suggestion.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I am using the latest version of SpyHunt
          required: true
        - label: I have searched existing issues to ensure this feature has not already been requested
          required: true
        - label: I have read the [documentation](https://spyhunt.readthedocs.io) to confirm this feature doesn't already exist
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Vulnerability Scanner
        - Enhancement to Existing Scanner
        - New Reconnaissance Module
        - Performance Improvement
        - User Interface/UX Improvement
        - API/Integration Enhancement
        - Documentation Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        Is your feature request related to a problem? Please describe.
        Example: "I'm frustrated when..."
      placeholder: Describe the problem or use case...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe the solution you'd like to see.
        Be as specific as possible about how this feature should work.
      placeholder: I would like SpyHunt to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds?
        Are there other tools that implement this feature?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: |
        How would this feature benefit SpyHunt users?
        Who would benefit from this feature?
      placeholder: |
        This feature would help security professionals to...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Use Cases / Examples
      description: |
        Provide specific examples or use cases where this feature would be useful.
        If possible, include example commands or expected output.
      placeholder: |
        Example usage:
        ```bash
        spyhunt --new-feature target.com
        ```

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: |
        If you have ideas about how this could be implemented, share them here.
        This is optional but can be very helpful!
      placeholder: |
        This could potentially be implemented by...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or references about the feature request here.
        Links to similar features in other tools, research papers, or documentation are helpful.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request to implement this feature
