name: Security Vulnerability (Public Disclosure)
description: Report a security vulnerability that has already been disclosed or is low severity
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT SECURITY NOTICE
        
        **STOP!** Before proceeding, please read carefully:
        
        - **For CRITICAL or HIGH severity vulnerabilities**: Do NOT create a public issue
        - **For unreported vulnerabilities**: Do NOT disclose them here
        - **For sensitive security issues**: Email pymmdrza@gmail.com directly
        
        This template should ONLY be used for:
        - Low severity security concerns
        - Already publicly disclosed vulnerabilities in dependencies
        - Security enhancements that don't expose existing vulnerabilities
        
        See our [Security Policy](https://github.com/Pymmdrza/SpyHunt/blob/main/.github/SECURITY.md) for more information.

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Acknowledgment
      description: Please confirm you understand when to use this template
      options:
        - label: I confirm this is NOT a critical/high severity vulnerability
          required: true
        - label: I confirm this vulnerability is already publicly disclosed OR is a low-severity enhancement suggestion
          required: true
        - label: I have read the Security Policy and understand that sensitive vulnerabilities should be emailed privately
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: What is the severity of this security concern?
      options:
        - Low - Minor security enhancement
        - Informational - Best practice suggestion
        - Dependency vulnerability (already public)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security concern or enhancement
      placeholder: Describe the security issue or enhancement...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security concern is this?
      options:
        - Dependency Vulnerability
        - Code Quality / Best Practices
        - Security Enhancement
        - Documentation / Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact if this issue is not addressed?
      placeholder: |
        - Affected components: 
        - Risk level:
        - Potential consequences:
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of SpyHunt are affected?
      placeholder: "e.g., All versions, 4.0.x, specific version numbers"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If applicable, provide steps to reproduce the security concern
      placeholder: |
        1. 
        2. 
        3. 

  - type: textarea
    id: remediation
    attributes:
      label: Suggested Remediation
      description: |
        If you have suggestions for how to address this security concern, please share them.
      placeholder: |
        This could be addressed by...

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Include any relevant references, CVEs, security advisories, or documentation
      placeholder: |
        - CVE-XXXX-XXXXX
        - Link to security advisory
        - Related documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the security concern here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this security issue?
      options:
        - label: I am willing to submit a pull request to address this security concern
